// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final VarHandle const$0 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("DynamicRangeSetting"));
    static final VarHandle const$1 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("DevelopmentDynamicRange"));
    static final VarHandle const$2 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("AutoDynamicRange"));
    static final VarHandle const$3 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("DRangePriority"));
    static final VarHandle const$4 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("DRangePriorityAuto"));
    static final VarHandle const$5 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("DRangePriorityFixed"));
}


