// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final VarHandle const$0 = constants$33.const$3.varHandle(MemoryLayout.PathElement.groupElement("FlashExposureCompensation4"));
    static final VarHandle const$1 = constants$33.const$3.varHandle(MemoryLayout.PathElement.groupElement("FlashSource"));
    static final VarHandle const$2 = constants$33.const$3.varHandle(MemoryLayout.PathElement.groupElement("ExternalFlashFlags"));
    static final VarHandle const$3 = constants$33.const$3.varHandle(MemoryLayout.PathElement.groupElement("FlashControlCommanderMode"));
    static final VarHandle const$4 = constants$33.const$3.varHandle(MemoryLayout.PathElement.groupElement("FlashOutputAndCompensation"));
    static final VarHandle const$5 = constants$33.const$3.varHandle(MemoryLayout.PathElement.groupElement("FlashFocalLength"));
}


