// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final VarHandle const$0 = constants$20.const$5.varHandle(MemoryLayout.PathElement.groupElement("FlashMode"));
    static final VarHandle const$1 = constants$20.const$5.varHandle(MemoryLayout.PathElement.groupElement("FlashActivity"));
    static final VarHandle const$2 = constants$20.const$5.varHandle(MemoryLayout.PathElement.groupElement("FlashBits"));
    static final VarHandle const$3 = constants$20.const$5.varHandle(MemoryLayout.PathElement.groupElement("ManualFlashOutput"));
    static final VarHandle const$4 = constants$20.const$5.varHandle(MemoryLayout.PathElement.groupElement("FlashOutput"));
    static final VarHandle const$5 = constants$20.const$5.varHandle(MemoryLayout.PathElement.groupElement("FlashGuideNumber"));
}


