// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    static final VarHandle const$0 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("uncropped"));
    static final VarHandle const$1 = constants$26.const$0.varHandle(MemoryLayout.PathElement.groupElement("format"));
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("ExpoMidPointShift"),
        JAVA_SHORT.withName("DynamicRange"),
        JAVA_SHORT.withName("FilmMode"),
        JAVA_SHORT.withName("DynamicRangeSetting"),
        JAVA_SHORT.withName("DevelopmentDynamicRange"),
        JAVA_SHORT.withName("AutoDynamicRange"),
        JAVA_SHORT.withName("DRangePriority"),
        JAVA_SHORT.withName("DRangePriorityAuto"),
        JAVA_SHORT.withName("DRangePriorityFixed"),
        JAVA_FLOAT.withName("BrightnessCompensation"),
        JAVA_SHORT.withName("FocusMode"),
        JAVA_SHORT.withName("AFMode"),
        MemoryLayout.sequenceLayout(2, JAVA_SHORT).withName("FocusPixel"),
        JAVA_SHORT.withName("PrioritySettings"),
        MemoryLayout.paddingLayout(2),
        JAVA_INT.withName("FocusSettings"),
        JAVA_INT.withName("AF_C_Settings"),
        JAVA_SHORT.withName("FocusWarning"),
        MemoryLayout.sequenceLayout(3, JAVA_SHORT).withName("ImageStabilization"),
        JAVA_SHORT.withName("FlashMode"),
        JAVA_SHORT.withName("WB_Preset"),
        JAVA_SHORT.withName("ShutterType"),
        JAVA_SHORT.withName("ExrMode"),
        JAVA_SHORT.withName("Macro"),
        MemoryLayout.paddingLayout(2),
        JAVA_INT.withName("Rating"),
        JAVA_SHORT.withName("CropMode"),
        MemoryLayout.sequenceLayout(13, JAVA_BYTE).withName("SerialSignature"),
        MemoryLayout.sequenceLayout(5, JAVA_BYTE).withName("SensorID"),
        MemoryLayout.sequenceLayout(5, JAVA_BYTE).withName("RAFVersion"),
        MemoryLayout.paddingLayout(3),
        JAVA_INT.withName("RAFDataGeneration"),
        JAVA_SHORT.withName("RAFDataVersion"),
        MemoryLayout.paddingLayout(2),
        JAVA_INT.withName("isTSNERDTS"),
        JAVA_SHORT.withName("DriveMode"),
        MemoryLayout.sequenceLayout(9, JAVA_SHORT).withName("BlackLevel"),
        MemoryLayout.sequenceLayout(32, JAVA_INT).withName("RAFData_ImageSizeTable"),
        JAVA_INT.withName("AutoBracketing"),
        JAVA_INT.withName("SequenceNumber"),
        JAVA_INT.withName("SeriesLength"),
        MemoryLayout.sequenceLayout(2, JAVA_FLOAT).withName("PixelShiftOffset"),
        JAVA_INT.withName("ImageCount")
    ).withName("libraw_fuji_info_t");
    static final VarHandle const$3 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("ExpoMidPointShift"));
    static final VarHandle const$4 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("DynamicRange"));
    static final VarHandle const$5 = constants$27.const$2.varHandle(MemoryLayout.PathElement.groupElement("FilmMode"));
}


