// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$10 {

    static final FunctionDescriptor libraw_get_iheight$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle libraw_get_iheight$MH = RuntimeHelper.downcallHandle(
        libraw_h.LIBRARIES, "libraw_get_iheight",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$10.libraw_get_iheight$FUNC, false
    );
    static final FunctionDescriptor libraw_get_iwidth$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle libraw_get_iwidth$MH = RuntimeHelper.downcallHandle(
        libraw_h.LIBRARIES, "libraw_get_iwidth",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$10.libraw_get_iwidth$FUNC, false
    );
    static final FunctionDescriptor libraw_get_cam_mul$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle libraw_get_cam_mul$MH = RuntimeHelper.downcallHandle(
        libraw_h.LIBRARIES, "libraw_get_cam_mul",
        "(Ljdk/incubator/foreign/MemoryAddress;I)F",
        constants$10.libraw_get_cam_mul$FUNC, false
    );
    static final FunctionDescriptor libraw_get_pre_mul$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle libraw_get_pre_mul$MH = RuntimeHelper.downcallHandle(
        libraw_h.LIBRARIES, "libraw_get_pre_mul",
        "(Ljdk/incubator/foreign/MemoryAddress;I)F",
        constants$10.libraw_get_pre_mul$FUNC, false
    );
    static final FunctionDescriptor libraw_get_rgb_cam$FUNC = FunctionDescriptor.of(C_FLOAT,
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle libraw_get_rgb_cam$MH = RuntimeHelper.downcallHandle(
        libraw_h.LIBRARIES, "libraw_get_rgb_cam",
        "(Ljdk/incubator/foreign/MemoryAddress;II)F",
        constants$10.libraw_get_rgb_cam$FUNC, false
    );
    static final FunctionDescriptor libraw_get_color_maximum$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle libraw_get_color_maximum$MH = RuntimeHelper.downcallHandle(
        libraw_h.LIBRARIES, "libraw_get_color_maximum",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$10.libraw_get_color_maximum$FUNC, false
    );
}


