// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$65 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$65() {}
    static final VarHandle const$0 = constants$64.const$4.varHandle(MemoryLayout.PathElement.groupElement("AFInfoData_order"));
    static final VarHandle const$1 = constants$64.const$4.varHandle(MemoryLayout.PathElement.groupElement("AFInfoData_version"));
    static final VarHandle const$2 = constants$64.const$4.varHandle(MemoryLayout.PathElement.groupElement("AFInfoData_length"));
    static final VarHandle const$3 = constants$64.const$4.varHandle(MemoryLayout.PathElement.groupElement("AFInfoData"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_FLOAT.withName("FlashEC"),
        JAVA_FLOAT.withName("FlashGN"),
        JAVA_FLOAT.withName("CameraTemperature"),
        JAVA_FLOAT.withName("SensorTemperature"),
        JAVA_FLOAT.withName("SensorTemperature2"),
        JAVA_FLOAT.withName("LensTemperature"),
        JAVA_FLOAT.withName("AmbientTemperature"),
        JAVA_FLOAT.withName("BatteryTemperature"),
        JAVA_FLOAT.withName("exifAmbientTemperature"),
        JAVA_FLOAT.withName("exifHumidity"),
        JAVA_FLOAT.withName("exifPressure"),
        JAVA_FLOAT.withName("exifWaterDepth"),
        JAVA_FLOAT.withName("exifAcceleration"),
        JAVA_FLOAT.withName("exifCameraElevationAngle"),
        JAVA_FLOAT.withName("real_ISO"),
        JAVA_FLOAT.withName("exifExposureIndex"),
        JAVA_SHORT.withName("ColorSpace"),
        MemoryLayout.sequenceLayout(128, JAVA_BYTE).withName("firmware"),
        MemoryLayout.paddingLayout(2),
        JAVA_FLOAT.withName("ExposureCalibrationShift"),
        MemoryLayout.sequenceLayout(4, MemoryLayout.structLayout(
            JAVA_INT.withName("AFInfoData_tag"),
            JAVA_SHORT.withName("AFInfoData_order"),
            MemoryLayout.paddingLayout(2),
            JAVA_INT.withName("AFInfoData_version"),
            JAVA_INT.withName("AFInfoData_length"),
            RuntimeHelper.POINTER.withName("AFInfoData")
        ).withName("libraw_afinfo_item_t")).withName("afdata"),
        JAVA_INT.withName("afcount"),
        MemoryLayout.paddingLayout(4)
    ).withName("libraw_metadata_common_t");
    static final VarHandle const$5 = constants$65.const$4.varHandle(MemoryLayout.PathElement.groupElement("FlashEC"));
}


