// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$43 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$43() {}
    static final VarHandle const$0 = constants$42.const$3.varHandle(MemoryLayout.PathElement.groupElement("Multishot"));
    static final VarHandle const$1 = constants$42.const$3.varHandle(MemoryLayout.PathElement.groupElement("gamma"));
    static final VarHandle const$2 = constants$42.const$3.varHandle(MemoryLayout.PathElement.groupElement("FocusStepNear"));
    static final VarHandle const$3 = constants$42.const$3.varHandle(MemoryLayout.PathElement.groupElement("FocusStepCount"));
    static final VarHandle const$4 = constants$42.const$3.varHandle(MemoryLayout.PathElement.groupElement("ZoomPosition"));
    static final VarHandle const$5 = constants$42.const$3.varHandle(MemoryLayout.PathElement.groupElement("LensManufacturer"));
}


