// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$8 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$8() {}
    static final FunctionDescriptor libraw_COLOR$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle libraw_COLOR$MH = RuntimeHelper.downcallHandle(
        "libraw_COLOR",
        constants$8.libraw_COLOR$FUNC
    );
    static final FunctionDescriptor libraw_capabilities$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle libraw_capabilities$MH = RuntimeHelper.downcallHandleVariadic(
        "libraw_capabilities",
        constants$8.libraw_capabilities$FUNC
    );
    static final FunctionDescriptor libraw_adjust_sizes_info_only$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_adjust_sizes_info_only$MH = RuntimeHelper.downcallHandle(
        "libraw_adjust_sizes_info_only",
        constants$8.libraw_adjust_sizes_info_only$FUNC
    );
    static final FunctionDescriptor libraw_dcraw_ppm_tiff_writer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_dcraw_ppm_tiff_writer$MH = RuntimeHelper.downcallHandle(
        "libraw_dcraw_ppm_tiff_writer",
        constants$8.libraw_dcraw_ppm_tiff_writer$FUNC
    );
    static final FunctionDescriptor libraw_dcraw_thumb_writer$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_dcraw_thumb_writer$MH = RuntimeHelper.downcallHandle(
        "libraw_dcraw_thumb_writer",
        constants$8.libraw_dcraw_thumb_writer$FUNC
    );
    static final FunctionDescriptor libraw_dcraw_process$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_dcraw_process$MH = RuntimeHelper.downcallHandle(
        "libraw_dcraw_process",
        constants$8.libraw_dcraw_process$FUNC
    );
}


