// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct libraw_pentax_makernotes_t {
 *     unsigned char DriveMode[4];
 *     unsigned short FocusMode[2];
 *     unsigned short AFPointSelected[2];
 *     unsigned short AFPointSelected_Area;
 *     int AFPointsInFocus_version;
 *     unsigned int AFPointsInFocus;
 *     unsigned short FocusPosition;
 *     short AFAdjustment;
 *     unsigned char AFPointMode;
 *     unsigned char MultiExposure;
 *     unsigned short Quality;
 * };
 * }
 */
public class libraw_pentax_makernotes_t {

    public static MemoryLayout $LAYOUT() {
        return constants$44.const$0;
    }
    public static MemorySegment DriveMode$slice(MemorySegment seg) {
        return seg.asSlice(0, 4);
    }
    public static MemorySegment FocusMode$slice(MemorySegment seg) {
        return seg.asSlice(4, 4);
    }
    public static MemorySegment AFPointSelected$slice(MemorySegment seg) {
        return seg.asSlice(8, 4);
    }
    public static VarHandle AFPointSelected_Area$VH() {
        return constants$44.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short AFPointSelected_Area;
     * }
     */
    public static short AFPointSelected_Area$get(MemorySegment seg) {
        return (short)constants$44.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short AFPointSelected_Area;
     * }
     */
    public static void AFPointSelected_Area$set(MemorySegment seg, short x) {
        constants$44.const$1.set(seg, x);
    }
    public static short AFPointSelected_Area$get(MemorySegment seg, long index) {
        return (short)constants$44.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void AFPointSelected_Area$set(MemorySegment seg, long index, short x) {
        constants$44.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle AFPointsInFocus_version$VH() {
        return constants$44.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int AFPointsInFocus_version;
     * }
     */
    public static int AFPointsInFocus_version$get(MemorySegment seg) {
        return (int)constants$44.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int AFPointsInFocus_version;
     * }
     */
    public static void AFPointsInFocus_version$set(MemorySegment seg, int x) {
        constants$44.const$2.set(seg, x);
    }
    public static int AFPointsInFocus_version$get(MemorySegment seg, long index) {
        return (int)constants$44.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void AFPointsInFocus_version$set(MemorySegment seg, long index, int x) {
        constants$44.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle AFPointsInFocus$VH() {
        return constants$44.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int AFPointsInFocus;
     * }
     */
    public static int AFPointsInFocus$get(MemorySegment seg) {
        return (int)constants$44.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int AFPointsInFocus;
     * }
     */
    public static void AFPointsInFocus$set(MemorySegment seg, int x) {
        constants$44.const$3.set(seg, x);
    }
    public static int AFPointsInFocus$get(MemorySegment seg, long index) {
        return (int)constants$44.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void AFPointsInFocus$set(MemorySegment seg, long index, int x) {
        constants$44.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle FocusPosition$VH() {
        return constants$44.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short FocusPosition;
     * }
     */
    public static short FocusPosition$get(MemorySegment seg) {
        return (short)constants$44.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short FocusPosition;
     * }
     */
    public static void FocusPosition$set(MemorySegment seg, short x) {
        constants$44.const$4.set(seg, x);
    }
    public static short FocusPosition$get(MemorySegment seg, long index) {
        return (short)constants$44.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void FocusPosition$set(MemorySegment seg, long index, short x) {
        constants$44.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle AFAdjustment$VH() {
        return constants$44.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * short AFAdjustment;
     * }
     */
    public static short AFAdjustment$get(MemorySegment seg) {
        return (short)constants$44.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * short AFAdjustment;
     * }
     */
    public static void AFAdjustment$set(MemorySegment seg, short x) {
        constants$44.const$5.set(seg, x);
    }
    public static short AFAdjustment$get(MemorySegment seg, long index) {
        return (short)constants$44.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void AFAdjustment$set(MemorySegment seg, long index, short x) {
        constants$44.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle AFPointMode$VH() {
        return constants$45.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned char AFPointMode;
     * }
     */
    public static byte AFPointMode$get(MemorySegment seg) {
        return (byte)constants$45.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned char AFPointMode;
     * }
     */
    public static void AFPointMode$set(MemorySegment seg, byte x) {
        constants$45.const$0.set(seg, x);
    }
    public static byte AFPointMode$get(MemorySegment seg, long index) {
        return (byte)constants$45.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void AFPointMode$set(MemorySegment seg, long index, byte x) {
        constants$45.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle MultiExposure$VH() {
        return constants$45.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned char MultiExposure;
     * }
     */
    public static byte MultiExposure$get(MemorySegment seg) {
        return (byte)constants$45.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned char MultiExposure;
     * }
     */
    public static void MultiExposure$set(MemorySegment seg, byte x) {
        constants$45.const$1.set(seg, x);
    }
    public static byte MultiExposure$get(MemorySegment seg, long index) {
        return (byte)constants$45.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void MultiExposure$set(MemorySegment seg, long index, byte x) {
        constants$45.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle Quality$VH() {
        return constants$45.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short Quality;
     * }
     */
    public static short Quality$get(MemorySegment seg) {
        return (short)constants$45.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short Quality;
     * }
     */
    public static void Quality$set(MemorySegment seg, short x) {
        constants$45.const$2.set(seg, x);
    }
    public static short Quality$get(MemorySegment seg, long index) {
        return (short)constants$45.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void Quality$set(MemorySegment seg, long index, short x) {
        constants$45.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


