// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct libraw_kodak_makernotes_t {
 *     unsigned short BlackLevelTop;
 *     unsigned short BlackLevelBottom;
 *     short offset_left;
 *     short offset_top;
 *     unsigned short clipBlack;
 *     unsigned short clipWhite;
 *     float  romm_camDaylight[3][3];
 *     float  romm_camTungsten[3][3];
 *     float  romm_camFluorescent[3][3];
 *     float  romm_camFlash[3][3];
 *     float  romm_camCustom[3][3];
 *     float  romm_camAuto[3][3];
 *     unsigned short val018percent;
 *     unsigned short val100percent;
 *     unsigned short val170percent;
 *     short MakerNoteKodak8a;
 *     float ISOCalibrationGain;
 *     float AnalogISO;
 * };
 * }
 */
public class libraw_kodak_makernotes_t {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("BlackLevelTop"),
        Constants$root.C_SHORT$LAYOUT.withName("BlackLevelBottom"),
        Constants$root.C_SHORT$LAYOUT.withName("offset_left"),
        Constants$root.C_SHORT$LAYOUT.withName("offset_top"),
        Constants$root.C_SHORT$LAYOUT.withName("clipBlack"),
        Constants$root.C_SHORT$LAYOUT.withName("clipWhite"),
        MemoryLayout.sequenceLayout(3, MemoryLayout.sequenceLayout(3, Constants$root.C_FLOAT$LAYOUT)).withName("romm_camDaylight"),
        MemoryLayout.sequenceLayout(3, MemoryLayout.sequenceLayout(3, Constants$root.C_FLOAT$LAYOUT)).withName("romm_camTungsten"),
        MemoryLayout.sequenceLayout(3, MemoryLayout.sequenceLayout(3, Constants$root.C_FLOAT$LAYOUT)).withName("romm_camFluorescent"),
        MemoryLayout.sequenceLayout(3, MemoryLayout.sequenceLayout(3, Constants$root.C_FLOAT$LAYOUT)).withName("romm_camFlash"),
        MemoryLayout.sequenceLayout(3, MemoryLayout.sequenceLayout(3, Constants$root.C_FLOAT$LAYOUT)).withName("romm_camCustom"),
        MemoryLayout.sequenceLayout(3, MemoryLayout.sequenceLayout(3, Constants$root.C_FLOAT$LAYOUT)).withName("romm_camAuto"),
        Constants$root.C_SHORT$LAYOUT.withName("val018percent"),
        Constants$root.C_SHORT$LAYOUT.withName("val100percent"),
        Constants$root.C_SHORT$LAYOUT.withName("val170percent"),
        Constants$root.C_SHORT$LAYOUT.withName("MakerNoteKodak8a"),
        Constants$root.C_FLOAT$LAYOUT.withName("ISOCalibrationGain"),
        Constants$root.C_FLOAT$LAYOUT.withName("AnalogISO")
    ).withName("libraw_kodak_makernotes_t");
    public static MemoryLayout $LAYOUT() {
        return libraw_kodak_makernotes_t.$struct$LAYOUT;
    }
    static final VarHandle BlackLevelTop$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("BlackLevelTop"));
    public static VarHandle BlackLevelTop$VH() {
        return libraw_kodak_makernotes_t.BlackLevelTop$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short BlackLevelTop;
     * }
     */
    public static short BlackLevelTop$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.BlackLevelTop$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short BlackLevelTop;
     * }
     */
    public static void BlackLevelTop$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.BlackLevelTop$VH.set(seg, x);
    }
    public static short BlackLevelTop$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.BlackLevelTop$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void BlackLevelTop$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.BlackLevelTop$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle BlackLevelBottom$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("BlackLevelBottom"));
    public static VarHandle BlackLevelBottom$VH() {
        return libraw_kodak_makernotes_t.BlackLevelBottom$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short BlackLevelBottom;
     * }
     */
    public static short BlackLevelBottom$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.BlackLevelBottom$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short BlackLevelBottom;
     * }
     */
    public static void BlackLevelBottom$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.BlackLevelBottom$VH.set(seg, x);
    }
    public static short BlackLevelBottom$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.BlackLevelBottom$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void BlackLevelBottom$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.BlackLevelBottom$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle offset_left$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("offset_left"));
    public static VarHandle offset_left$VH() {
        return libraw_kodak_makernotes_t.offset_left$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * short offset_left;
     * }
     */
    public static short offset_left$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.offset_left$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * short offset_left;
     * }
     */
    public static void offset_left$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.offset_left$VH.set(seg, x);
    }
    public static short offset_left$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.offset_left$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void offset_left$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.offset_left$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle offset_top$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("offset_top"));
    public static VarHandle offset_top$VH() {
        return libraw_kodak_makernotes_t.offset_top$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * short offset_top;
     * }
     */
    public static short offset_top$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.offset_top$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * short offset_top;
     * }
     */
    public static void offset_top$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.offset_top$VH.set(seg, x);
    }
    public static short offset_top$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.offset_top$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void offset_top$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.offset_top$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle clipBlack$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("clipBlack"));
    public static VarHandle clipBlack$VH() {
        return libraw_kodak_makernotes_t.clipBlack$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short clipBlack;
     * }
     */
    public static short clipBlack$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.clipBlack$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short clipBlack;
     * }
     */
    public static void clipBlack$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.clipBlack$VH.set(seg, x);
    }
    public static short clipBlack$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.clipBlack$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void clipBlack$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.clipBlack$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle clipWhite$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("clipWhite"));
    public static VarHandle clipWhite$VH() {
        return libraw_kodak_makernotes_t.clipWhite$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short clipWhite;
     * }
     */
    public static short clipWhite$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.clipWhite$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short clipWhite;
     * }
     */
    public static void clipWhite$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.clipWhite$VH.set(seg, x);
    }
    public static short clipWhite$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.clipWhite$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void clipWhite$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.clipWhite$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment romm_camDaylight$slice(MemorySegment seg) {
        return seg.asSlice(12, 36);
    }
    public static MemorySegment romm_camTungsten$slice(MemorySegment seg) {
        return seg.asSlice(48, 36);
    }
    public static MemorySegment romm_camFluorescent$slice(MemorySegment seg) {
        return seg.asSlice(84, 36);
    }
    public static MemorySegment romm_camFlash$slice(MemorySegment seg) {
        return seg.asSlice(120, 36);
    }
    public static MemorySegment romm_camCustom$slice(MemorySegment seg) {
        return seg.asSlice(156, 36);
    }
    public static MemorySegment romm_camAuto$slice(MemorySegment seg) {
        return seg.asSlice(192, 36);
    }
    static final VarHandle val018percent$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("val018percent"));
    public static VarHandle val018percent$VH() {
        return libraw_kodak_makernotes_t.val018percent$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short val018percent;
     * }
     */
    public static short val018percent$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.val018percent$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short val018percent;
     * }
     */
    public static void val018percent$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.val018percent$VH.set(seg, x);
    }
    public static short val018percent$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.val018percent$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void val018percent$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.val018percent$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle val100percent$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("val100percent"));
    public static VarHandle val100percent$VH() {
        return libraw_kodak_makernotes_t.val100percent$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short val100percent;
     * }
     */
    public static short val100percent$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.val100percent$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short val100percent;
     * }
     */
    public static void val100percent$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.val100percent$VH.set(seg, x);
    }
    public static short val100percent$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.val100percent$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void val100percent$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.val100percent$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle val170percent$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("val170percent"));
    public static VarHandle val170percent$VH() {
        return libraw_kodak_makernotes_t.val170percent$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short val170percent;
     * }
     */
    public static short val170percent$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.val170percent$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short val170percent;
     * }
     */
    public static void val170percent$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.val170percent$VH.set(seg, x);
    }
    public static short val170percent$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.val170percent$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void val170percent$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.val170percent$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle MakerNoteKodak8a$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("MakerNoteKodak8a"));
    public static VarHandle MakerNoteKodak8a$VH() {
        return libraw_kodak_makernotes_t.MakerNoteKodak8a$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * short MakerNoteKodak8a;
     * }
     */
    public static short MakerNoteKodak8a$get(MemorySegment seg) {
        return (short)libraw_kodak_makernotes_t.MakerNoteKodak8a$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * short MakerNoteKodak8a;
     * }
     */
    public static void MakerNoteKodak8a$set(MemorySegment seg, short x) {
        libraw_kodak_makernotes_t.MakerNoteKodak8a$VH.set(seg, x);
    }
    public static short MakerNoteKodak8a$get(MemorySegment seg, long index) {
        return (short)libraw_kodak_makernotes_t.MakerNoteKodak8a$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void MakerNoteKodak8a$set(MemorySegment seg, long index, short x) {
        libraw_kodak_makernotes_t.MakerNoteKodak8a$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle ISOCalibrationGain$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("ISOCalibrationGain"));
    public static VarHandle ISOCalibrationGain$VH() {
        return libraw_kodak_makernotes_t.ISOCalibrationGain$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float ISOCalibrationGain;
     * }
     */
    public static float ISOCalibrationGain$get(MemorySegment seg) {
        return (float)libraw_kodak_makernotes_t.ISOCalibrationGain$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float ISOCalibrationGain;
     * }
     */
    public static void ISOCalibrationGain$set(MemorySegment seg, float x) {
        libraw_kodak_makernotes_t.ISOCalibrationGain$VH.set(seg, x);
    }
    public static float ISOCalibrationGain$get(MemorySegment seg, long index) {
        return (float)libraw_kodak_makernotes_t.ISOCalibrationGain$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ISOCalibrationGain$set(MemorySegment seg, long index, float x) {
        libraw_kodak_makernotes_t.ISOCalibrationGain$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle AnalogISO$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("AnalogISO"));
    public static VarHandle AnalogISO$VH() {
        return libraw_kodak_makernotes_t.AnalogISO$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float AnalogISO;
     * }
     */
    public static float AnalogISO$get(MemorySegment seg) {
        return (float)libraw_kodak_makernotes_t.AnalogISO$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float AnalogISO;
     * }
     */
    public static void AnalogISO$set(MemorySegment seg, float x) {
        libraw_kodak_makernotes_t.AnalogISO$VH.set(seg, x);
    }
    public static float AnalogISO$get(MemorySegment seg, long index) {
        return (float)libraw_kodak_makernotes_t.AnalogISO$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void AnalogISO$set(MemorySegment seg, long index, float x) {
        libraw_kodak_makernotes_t.AnalogISO$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


