// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct output_data_t {
 *     int *histogram[8192];
 *     unsigned int* oprof;
 * };
 * }
 */
public class output_data_t {

    public static MemoryLayout $LAYOUT() {
        return constants$93.const$4;
    }
    public static VarHandle histogram$VH() {
        return constants$93.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int *histogram[8192];
     * }
     */
    public static MemorySegment histogram$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$93.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int *histogram[8192];
     * }
     */
    public static void histogram$set(MemorySegment seg, MemorySegment x) {
        constants$93.const$5.set(seg, x);
    }
    public static MemorySegment histogram$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$93.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void histogram$set(MemorySegment seg, long index, MemorySegment x) {
        constants$93.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle oprof$VH() {
        return constants$94.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int* oprof;
     * }
     */
    public static MemorySegment oprof$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$94.const$0.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int* oprof;
     * }
     */
    public static void oprof$set(MemorySegment seg, MemorySegment x) {
        constants$94.const$0.set(seg, x);
    }
    public static MemorySegment oprof$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$94.const$0.get(seg.asSlice(index*sizeof()));
    }
    public static void oprof$set(MemorySegment seg, long index, MemorySegment x) {
        constants$94.const$0.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


