// Generated by jextract

package org.libraw.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface pre_identify_callback {

    int apply(jdk.incubator.foreign.MemoryAddress x0);
    static NativeSymbol allocate(pre_identify_callback fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(pre_identify_callback.class, fi, constants$1.pre_identify_callback$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static pre_identify_callback ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("pre_identify_callback::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress x0) -> {
            try {
                return (int)constants$1.pre_identify_callback$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


