// Generated by jextract

package org.libraw.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$120 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$120() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(libraw_set_exifparser_handler$cb.class, "apply", constants$2.const$0);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "libraw_set_exifparser_handler",
        constants$1.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(libraw_set_dataerror_handler$func.class, "apply", constants$2.const$4);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "libraw_set_dataerror_handler",
        constants$1.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(libraw_set_progress_handler$cb.class, "apply", constants$3.const$2);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "libraw_set_progress_handler",
        constants$1.const$3
    );
}


