// Generated by jextract

package org.libraw.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$54 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$54() {}
    static final VarHandle const$0 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("VariableLowPassFilter"));
    static final VarHandle const$1 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("LongExposureNoiseReduction"));
    static final VarHandle const$2 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("HighISONoiseReduction"));
    static final VarHandle const$3 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("group2010"));
    static final VarHandle const$4 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("group9050"));
    static final VarHandle const$5 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("real_iso_offset"));
}


