// Generated by jextract

package org.libraw.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$5 {

    static final FunctionDescriptor libraw_raw2image$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_raw2image$MH = RuntimeHelper.downcallHandle(
        "libraw_raw2image",
        constants$5.libraw_raw2image$FUNC, false
    );
    static final FunctionDescriptor libraw_free_image$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_free_image$MH = RuntimeHelper.downcallHandle(
        "libraw_free_image",
        constants$5.libraw_free_image$FUNC, false
    );
    static final FunctionDescriptor libraw_version$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle libraw_version$MH = RuntimeHelper.downcallHandle(
        "libraw_version",
        constants$5.libraw_version$FUNC, true
    );
    static final FunctionDescriptor libraw_versionNumber$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle libraw_versionNumber$MH = RuntimeHelper.downcallHandle(
        "libraw_versionNumber",
        constants$5.libraw_versionNumber$FUNC, true
    );
    static final FunctionDescriptor libraw_cameraList$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle libraw_cameraList$MH = RuntimeHelper.downcallHandle(
        "libraw_cameraList",
        constants$5.libraw_cameraList$FUNC, true
    );
    static final FunctionDescriptor libraw_cameraCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
    static final MethodHandle libraw_cameraCount$MH = RuntimeHelper.downcallHandle(
        "libraw_cameraCount",
        constants$5.libraw_cameraCount$FUNC, true
    );
}


