// Generated by jextract

package org.libraw.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$9 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$9() {}
    static final FunctionDescriptor libraw_dcraw_process$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_dcraw_process$MH = RuntimeHelper.downcallHandle(
        "libraw_dcraw_process",
        constants$9.libraw_dcraw_process$FUNC
    );
    static final FunctionDescriptor libraw_dcraw_make_mem_image$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_dcraw_make_mem_image$MH = RuntimeHelper.downcallHandle(
        "libraw_dcraw_make_mem_image",
        constants$9.libraw_dcraw_make_mem_image$FUNC
    );
    static final FunctionDescriptor libraw_dcraw_make_mem_thumb$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_dcraw_make_mem_thumb$MH = RuntimeHelper.downcallHandle(
        "libraw_dcraw_make_mem_thumb",
        constants$9.libraw_dcraw_make_mem_thumb$FUNC
    );
    static final FunctionDescriptor libraw_dcraw_clear_mem$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle libraw_dcraw_clear_mem$MH = RuntimeHelper.downcallHandle(
        "libraw_dcraw_clear_mem",
        constants$9.libraw_dcraw_clear_mem$FUNC
    );
    static final FunctionDescriptor libraw_set_demosaic$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle libraw_set_demosaic$MH = RuntimeHelper.downcallHandle(
        "libraw_set_demosaic",
        constants$9.libraw_set_demosaic$FUNC
    );
    static final FunctionDescriptor libraw_set_output_color$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle libraw_set_output_color$MH = RuntimeHelper.downcallHandle(
        "libraw_set_output_color",
        constants$9.libraw_set_output_color$FUNC
    );
}


