// Generated by jextract

package org.libraw.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$51 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$51() {}
    static final VarHandle const$0 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("CameraType"));
    static final VarHandle const$1 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("Sony0x9400_version"));
    static final VarHandle const$2 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("Sony0x9400_ReleaseMode2"));
    static final VarHandle const$3 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("Sony0x9400_SequenceImageNumber"));
    static final VarHandle const$4 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("Sony0x9400_SequenceLength1"));
    static final VarHandle const$5 = constants$50.const$5.varHandle(MemoryLayout.PathElement.groupElement("Sony0x9400_SequenceFileNumber"));
}


