// Generated by jextract

package org.libraw.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct libraw_tiff_tag {
 *     unsigned short tag;
 *     unsigned short type;
 *     int count;
 *     union union (unnamed at ./libraw_internal.h:225:3) val;
 * };
 * }
 */
public class libraw_tiff_tag {

    static final StructLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_SHORT$LAYOUT.withName("tag"),
        Constants$root.C_SHORT$LAYOUT.withName("type"),
        Constants$root.C_LONG$LAYOUT.withName("count"),
        MemoryLayout.unionLayout(
            MemoryLayout.sequenceLayout(4, Constants$root.C_CHAR$LAYOUT).withName("c"),
            MemoryLayout.sequenceLayout(2, Constants$root.C_SHORT$LAYOUT).withName("s"),
            Constants$root.C_LONG$LAYOUT.withName("i")
        ).withName("val")
    ).withName("libraw_tiff_tag");
    public static MemoryLayout $LAYOUT() {
        return libraw_tiff_tag.$struct$LAYOUT;
    }
    static final VarHandle tag$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("tag"));
    public static VarHandle tag$VH() {
        return libraw_tiff_tag.tag$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short tag;
     * }
     */
    public static short tag$get(MemorySegment seg) {
        return (short)libraw_tiff_tag.tag$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short tag;
     * }
     */
    public static void tag$set(MemorySegment seg, short x) {
        libraw_tiff_tag.tag$VH.set(seg, x);
    }
    public static short tag$get(MemorySegment seg, long index) {
        return (short)libraw_tiff_tag.tag$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void tag$set(MemorySegment seg, long index, short x) {
        libraw_tiff_tag.tag$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("type"));
    public static VarHandle type$VH() {
        return libraw_tiff_tag.type$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short type;
     * }
     */
    public static short type$get(MemorySegment seg) {
        return (short)libraw_tiff_tag.type$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short type;
     * }
     */
    public static void type$set(MemorySegment seg, short x) {
        libraw_tiff_tag.type$VH.set(seg, x);
    }
    public static short type$get(MemorySegment seg, long index) {
        return (short)libraw_tiff_tag.type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void type$set(MemorySegment seg, long index, short x) {
        libraw_tiff_tag.type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle count$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("count"));
    public static VarHandle count$VH() {
        return libraw_tiff_tag.count$VH;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int count;
     * }
     */
    public static int count$get(MemorySegment seg) {
        return (int)libraw_tiff_tag.count$VH.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int count;
     * }
     */
    public static void count$set(MemorySegment seg, int x) {
        libraw_tiff_tag.count$VH.set(seg, x);
    }
    public static int count$get(MemorySegment seg, long index) {
        return (int)libraw_tiff_tag.count$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void count$set(MemorySegment seg, long index, int x) {
        libraw_tiff_tag.count$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, SegmentScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


