// Generated by jextract

package org.libraw.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct libraw_dng_color_t {
 *     unsigned int parsedfields;
 *     unsigned short illuminant;
 *     float  calibration[4][4];
 *     float  colormatrix[4][3];
 *     float  forwardmatrix[3][4];
 * };
 * }
 */
public class libraw_dng_color_t {

    public static MemoryLayout $LAYOUT() {
        return constants$19.const$0;
    }
    public static VarHandle parsedfields$VH() {
        return constants$19.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int parsedfields;
     * }
     */
    public static int parsedfields$get(MemorySegment seg) {
        return (int)constants$19.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int parsedfields;
     * }
     */
    public static void parsedfields$set(MemorySegment seg, int x) {
        constants$19.const$1.set(seg, x);
    }
    public static int parsedfields$get(MemorySegment seg, long index) {
        return (int)constants$19.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void parsedfields$set(MemorySegment seg, long index, int x) {
        constants$19.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle illuminant$VH() {
        return constants$19.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short illuminant;
     * }
     */
    public static short illuminant$get(MemorySegment seg) {
        return (short)constants$19.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short illuminant;
     * }
     */
    public static void illuminant$set(MemorySegment seg, short x) {
        constants$19.const$2.set(seg, x);
    }
    public static short illuminant$get(MemorySegment seg, long index) {
        return (short)constants$19.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void illuminant$set(MemorySegment seg, long index, short x) {
        constants$19.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment calibration$slice(MemorySegment seg) {
        return seg.asSlice(8, 64);
    }
    public static MemorySegment colormatrix$slice(MemorySegment seg) {
        return seg.asSlice(72, 48);
    }
    public static MemorySegment forwardmatrix$slice(MemorySegment seg) {
        return seg.asSlice(120, 48);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


